### ISSUE TITLE
[BUG] Error is misleading if sosreport file doesn't exist

### ISSUE THREAD

**Issue by jduncan-rva** [jduncan-rva/soscleaner#84]
[root@soscleaner-rhel-build soscleaner]# soscleaner sosreport.tar.xz
02-19 08:34:57 soscleaner CONSOLE: Log File Created at /tmp/soscleaner-1046737167944100.log
02-19 08:34:57 soscleaner WARNING: soscleaner is a tool to help obfuscate sensitive information from an existing sosreport.
02-19 08:34:57 soscleaner WARNING: Please review the content before passing it along to any third party.
02-19 08:34:57 soscleaner CONSOLE: Creating Loopback Network Entry
02-19 08:34:57 soscleaner CONSOLE: Beginning SOSReport Extraction
02-19 08:34:57 soscleaner ERROR: [Errno 2] No such file or directory: 'sosreport.tar.xz'
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/soscleaner.py", line 247, in _extract_sosreport
    p = tarfile.open(path, 'r')
  File "/usr/lib64/python2.7/tarfile.py", line 1660, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/lib64/python2.7/tarfile.py", line 1722, in gzopen
    fileobj = bltn_open(name, mode + "b")
IOError: [Errno 2] No such file or directory: 'sosreport.tar.xz'
02-19 08:34:57 soscleaner ERROR: ('DeCompressionError: Unable to De-Compress %s into %s', 'sosreport.tar.xz', '/tmp/soscleaner-origin-1046737167944100')
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/soscleaner.py", line 257, in _extract_sosreport
    raise Exception("DeCompressionError: Unable to De-Compress %s into %s", path, self.origin_path)
Exception: ('DeCompressionError: Unable to De-Compress %s into %s', 'sosreport.tar.xz', '/tmp/soscleaner-origin-1046737167944100')
Traceback (most recent call last):
  File "/usr/bin/soscleaner", line 5, in <module>
    pkg_resources.run_script('soscleaner==0.3.99', 'soscleaner')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/soscleaner-0.3.99-py2.7.egg/EGG-INFO/scripts/soscleaner", line 58, in <module>

  File "/usr/lib/python2.7/site-packages/soscleaner-0.3.99-py2.7.egg/EGG-INFO/scripts/soscleaner", line 54, in main

  File "build/bdist.linux-x86_64/egg/soscleaner.py", line 1281, in clean_report
  File "build/bdist.linux-x86_64/egg/soscleaner.py", line 261, in _extract_sosreport
Exception: CompressionError: Unable To Determine Compression Type

**Comment by slashdd** [comment]
Few scenarios tested so far with good results:

Non-existing sosreport
```
# soscleaner sosreport.tar.xz
ERROR: No presence of an existing file to sanitize detected
```
Non-existing sosreport with other parameters
```
# soscleaner -k patate -l DEBUG /tmp/sosreport-<REDACTED>-20190507192608.ta
ERROR: No presence of an existing file to sanitize detected
```
Existing sosreport with other parameters
```
soscleaner -k potato -l DEBUG /tmp/sosreport-<REDACTED>-20190507192608.tar.xz
05-09 10:30:20 soscleaner CONSOLE: Log File Created at /tmp/soscleaner-1021855178628664.log
```
Existing sosreport only
```
soscleaner sosreport-<REDACTED>-20190507192608.tar.xz
05-09 10:31:03 soscleaner CONSOLE: Log File Created at /tmp/soscleaner-3811814353527531.log

```
