### ISSUE TITLE
[BUG] Network option in conifg file reports exceptions if left blank

### ISSUE THREAD

**Issue by skhobbs18** [jduncan-rva/soscleaner#93]
**Describe the bug**
The network section of the config file will report exceptions if left blank.  The cleaner continues to run, it just reports the exeptions

**Expected behavior**
If there is no network configured, the section should be quietly ignored.

**Additional context**
Example tracebacks for different settings.

- No NetworkConfig section at all:
~~~
02-22 10:26:11 soscleaner ERROR: No section: 'NetworkConfig'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/soscleaner.py", line 176, in _read_later_config_options
    networks = config.get('NetworkConfig', 'networks')
  File "/usr/lib64/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
NoSectionError: No section: 'NetworkConfig'
~~~
- Blank NetworkConfig Section
~~~
02-22 10:31:03 soscleaner CONSOLE: Adding keyword file from config file - 
02-22 10:31:03 soscleaner ERROR: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/soscleaner.py", line 1173, in _ip4_parse_network
    net = IPv4Network(network)
  File "/usr/lib/python2.7/site-packages/ipaddr.py", line 1290, in __init__
    self._ip = self._ip_int_from_string(addr[0])
  File "/usr/lib/python2.7/site-packages/ipaddr.py", line 1042, in _ip_int_from_string
    raise AddressValueError(ip_str)
AddressValueError
02-22 10:31:03 soscleaner ERROR: ('IP4_PARSE_NETWORK_ERROR: Unable to parse network - %s', '')
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/soscleaner.py", line 1222, in _ip4_add_network
    net, netmask = self._ip4_parse_network(network)
  File "/usr/lib/python2.7/site-packages/soscleaner.py", line 1180, in _ip4_parse_network
    raise Exception("IP4_PARSE_NETWORK_ERROR: Unable to parse network - %s", network)
Exception: ('IP4_PARSE_NETWORK_ERROR: Unable to parse network - %s', '')
02-22 10:31:03 soscleaner ERROR: ('IP4_ADD_NETWORK_ERROR: Unable to add obfuscated network - %s', '')
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/soscleaner.py", line 180, in _read_later_config_options
    self._ip4_add_network(network)
  File "/usr/lib/python2.7/site-packages/soscleaner.py", line 1239, in _ip4_add_network
    raise Exception("IP4_ADD_NETWORK_ERROR: Unable to add obfuscated network - %s", network)
Exception: ('IP4_ADD_NETWORK_ERROR: Unable to add obfuscated network - %s', '')
02-22 10:31:03 soscleaner CONSOLE: Unable to load network config. Continuing
~~~

**Comment by jduncan-rva** [comment]
Fixed and refactored how config files are read. much cleaner now.
